// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_fields
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// To use environment variables, create a .env file in the project root
/// with your Firebase configuration values (see .env.example).
/// 
/// If .env is not loaded, fallback values will be used.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static String _getEnv(String key) {
    try {
      if (!dotenv.isInitialized) {
        return '';
      }
      return dotenv.env[key] ?? '';
    } catch (e) {
      return '';
    }
  }

  // Fallback values (original Firebase config)
  static const String _fallbackApiKeyWeb = 'AIzaSyBhh7fWTL9KGsJh611aug4np4h8nZX9R9w';
  static const String _fallbackApiKeyMobile = 'AIzaSyD-OWczs2aTIwxEIETkGGpW9KWwxTD3tsY';
  static const String _fallbackProjectId = 'manac-7339f';
  static const String _fallbackStorageBucket = 'manac-7339f.firebasestorage.app';
  static const String _fallbackMessagingSenderId = '790040261902';
  static const String _fallbackAppIdAndroid = '1:790040261902:android:e1ac0562c3bd0041a5935f';
  static const String _fallbackAppIdIos = '1:790040261902:ios:abcdef1234567890';
  static const String _fallbackAppIdWeb = '1:790040261902:web:db3f13a627e566d5a5935f';
  static const String _fallbackAuthDomain = 'manac-7339f.firebaseapp.com';
  // Realtime Database URL
  static const String _fallbackDatabaseURL = 'https://manac-7339f-default-rtdb.firebaseio.com';

  static FirebaseOptions get web {
    final apiKey = _getEnv('FIREBASE_API_KEY_WEB');
    return FirebaseOptions(
      apiKey: apiKey.isNotEmpty ? apiKey : _fallbackApiKeyWeb,
      appId: _fallbackAppIdWeb,
      messagingSenderId: _fallbackMessagingSenderId,
      projectId: _fallbackProjectId,
      authDomain: _fallbackAuthDomain,
      databaseURL: _fallbackDatabaseURL,
      storageBucket: _fallbackStorageBucket,
    );
  }

  static FirebaseOptions get android {
    final apiKey = _getEnv('FIREBASE_API_KEY_ANDROID');
    return FirebaseOptions(
      apiKey: apiKey.isNotEmpty ? apiKey : _fallbackApiKeyMobile,
      appId: _fallbackAppIdAndroid,
      messagingSenderId: _fallbackMessagingSenderId,
      projectId: _fallbackProjectId,
      databaseURL: _fallbackDatabaseURL,
      storageBucket: _fallbackStorageBucket,
    );
  }

  static FirebaseOptions get ios {
    final apiKey = _getEnv('FIREBASE_API_KEY_IOS');
    return FirebaseOptions(
      apiKey: apiKey.isNotEmpty ? apiKey : _fallbackApiKeyMobile,
      appId: _fallbackAppIdIos,
      messagingSenderId: _fallbackMessagingSenderId,
      projectId: _fallbackProjectId,
      databaseURL: _fallbackDatabaseURL,
      storageBucket: _fallbackStorageBucket,
    );
  }

  static FirebaseOptions get macos {
    final apiKey = _getEnv('FIREBASE_API_KEY_IOS');
    return FirebaseOptions(
      apiKey: apiKey.isNotEmpty ? apiKey : _fallbackApiKeyMobile,
      appId: _fallbackAppIdIos,
      messagingSenderId: _fallbackMessagingSenderId,
      projectId: _fallbackProjectId,
      databaseURL: _fallbackDatabaseURL,
      storageBucket: _fallbackStorageBucket,
    );
  }

  static FirebaseOptions get windows {
    return FirebaseOptions(
      apiKey: _fallbackApiKeyMobile,
      appId: _fallbackAppIdWeb,
      messagingSenderId: _fallbackMessagingSenderId,
      projectId: _fallbackProjectId,
      authDomain: _fallbackAuthDomain,
      databaseURL: _fallbackDatabaseURL,
      storageBucket: _fallbackStorageBucket,
    );
  }
}
