// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_fields
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhh7fWTL9KGsJh611aug4np4h8nZX9R9w',
    appId: '1:790040261902:web:db3f13a627e566d5a5935f',
    messagingSenderId: '790040261902',
    projectId: 'manac-7339f',
    authDomain: 'manac-7339f.firebaseapp.com',
    storageBucket: 'manac-7339f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-OWczs2aTIwxEIETkGGpW9KWwxTD3tsY',
    appId: '1:790040261902:android:e1ac0562c3bd0041a5935f',
    messagingSenderId: '790040261902',
    projectId: 'manac-7339f',
    storageBucket: 'manac-7339f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-OWczs2aTIwxEIETkGGpW9KWwxTD3tsY',
    appId: '1:790040261902:ios:abcdef1234567890',
    messagingSenderId: '790040261902',
    projectId: 'manac-7339f',
    storageBucket: 'manac-7339f.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-OWczs2aTIwxEIETkGGpW9KWwxTD3tsY',
    appId: '1:790040261902:ios:abcdef1234567890',
    messagingSenderId: '790040261902',
    projectId: 'manac-7339f',
    storageBucket: 'manac-7339f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-OWczs2aTIwxEIETkGGpW9KWwxTD3tsY',
    appId: '1:790040261902:windows:abcdef1234567890',
    messagingSenderId: '790040261902',
    projectId: 'manac-7339f',
    authDomain: 'manac-7339f.firebaseapp.com',
    storageBucket: 'manac-7339f.firebasestorage.app',
  );
}
