# Generated by Django 6.0.3 on 2026-03-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='checkout_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='overdue_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='reference_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
