# Generated by Django 4.2.30 on 2026-07-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0002_borrowing_checkout_email_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('checked_out', 'Emprunté'), ('returned', 'Retourné'), ('overdue', 'En retard')], default='pending', max_length=20),
        ),
    ]
