# Generated by Django 6.0.3 on 2026-03-22 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowings', '0002_borrowing_checkout_email_sent_and_more'),
        ('departments', '0001_initial'),
        ('equipment', '0002_alter_equipment_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_checkouts', models.PositiveIntegerField(default=0)),
                ('total_returns', models.PositiveIntegerField(default=0)),
                ('total_items_checked_out', models.PositiveIntegerField(default=0)),
                ('total_items_returned', models.PositiveIntegerField(default=0)),
                ('new_equipment_added', models.PositiveIntegerField(default=0)),
                ('equipment_maintenance', models.PositiveIntegerField(default=0)),
                ('stock_in_total', models.PositiveIntegerField(default=0)),
                ('stock_out_total', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('supplies', 'Supplies'), ('consumables', 'Consumables'), ('tools', 'Tools'), ('spare_parts', 'Spare Parts'), ('stationery', 'Stationery'), ('other', 'Other')], default='other', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('min_quantity', models.PositiveIntegerField(default=5)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('boxes', 'Boxes'), ('packs', 'Packs'), ('reams', 'Reams'), ('liters', 'Liters'), ('kg', 'Kilograms'), ('meters', 'Meters')], default='pcs', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(default='Main Warehouse', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_items', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='departments.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('stock_adjustment', 'Stock Adjustment'), ('equipment_checkout', 'Equipment Checkout'), ('equipment_return', 'Equipment Return'), ('sync', 'Sync'), ('login', 'Login'), ('logout', 'Logout'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('equipment_created', 'Equipment Created'), ('equipment_updated', 'Equipment Updated'), ('department_created', 'Department Created'), ('department_updated', 'Department Updated')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('borrowing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='borrowings.borrowing')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='equipment.equipment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.stockitem')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('quantity_before', models.PositiveIntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('borrowing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='borrowings.borrowing')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.stockitem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
